version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}  # optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always
    networks:
      - simple_postgres  # Specify the network name here

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always
    networks:
      - simple_postgres  # Specify the network name here

networks:
  simple_postgres:  # Define the network name here
    driver: bridge
